### ISSUE TITLE
Debugger not working after xcprepare integrate

### ISSUE THREAD

**Issue by cezarsignori** [spotify/XCRemoteCache#100]
**My integration setup**

[X] Automatic integration using `xcprepare integrate ...`

**Expected/desired behavior**

After running `xcprepare integrate --input {xcodeproj} --mode consumer` for each project in my application workspace, when I run my application, I expect the debugger to work.

**Minimal reproduction of the problem with instructions**

After running `xcprepare integrate --input {xcodeproj} --mode consumer` for each project in my application workspace, when I run my application the debugger no longer works. Most breakpoints become hollow and even for those that don't, the debugger does not stop. 

Step 1. Run `xcprepare integrate --input {xcodeproj} --mode consumer` for each project in the workspace;
Step 2. Run `rm -rf ~/Library/Developer/Xcode/DerivedData` and `rm -rf ~/Library/Caches/XCRemoteCache`;
Step 3. Open my workspace and hit run

**Consumer Logs**

<details>
When using `log show --predicate 'sender BEGINSWITH "xc"' --style compact --info --debug -last 7m` after running `xcprepare integrate`, I see no errors but 

```
E  xcodebuild[1023:573394] objc[1023]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1f798b6c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x1084c0318). One of the two will be used. Which one is undefined.
```

When using `log show --predicate 'sender BEGINSWITH "xc"' --style compact --info --debug -last 1m` after building my application I see no errors but 

```Couldn't verify if should disable RC for {commit}```
</details>

**Environment**

* **XCRemoteCache:** 0.3.7
* **HTTP cache server:** demo docker in localhost
* **Xcode:** 13.2.1 (13C100)

**Post build stats**

<details>
  <pre>
hit_count: 79
miss_count: 0
local_cache_bytes: 50233344
indexing_hit_count: 12
indexing_miss_count: 1
  </pre>
</details>

**Others**

I am on an Apple M1 Max with macOS Monterey 12.2.1 (21D62).

I am testing RC 0.3.7 on small application with 70 dependencies (across my own modules, git submodules and Pods committed to the repo).

Each xcodeproj has an associated manually created `.rcinfo` file with the following content:

```
primary_repo: {xcodeproj_repo}
cache_addresses:
- http://localhost:8080/cache
primary_branch: csignori/xcremotecache-proto
out_of_band_mappings: {
 'TOOLS_BUCK-OUT':'/Users/csignori/Projects/iphone/tools/config/buck-out',
 'CORE_MODULES_BUCK-OUT':'/Users/csignori/Projects/iphone/{root_project}/Modules/CoreModules/buck-out',
 'BDUX_BUCK-OUT':'/Users/csignori/Projects/iphone/{root_project}/Modules/Platform/Bdux/buck-out', 
 'MISC_BUCK-OUT':'/Users/csignori/Projects/iphone/{root_project}/Modules/Miscellaneous/buck-out', 
 'PODS_BUCK-OUT':'/Users/csignori/Projects/iphone/Pods/buck-out',
 'SUBMODULES_BUCK-OUT':'/Users/csignori/Projects/iphone/Submodules/buck-out',
 'ROOT_BUCK-OUT':'/Users/csignori/Projects/iphone/buck-out',
 'PODS':'/Users/csignori/Projects/iphone/Pods',
}
```

Besides checking the RC logs:

- I checked the `meta` files and they do not contain any absolute paths;
- My `~/.lldbinit` file is automatically created when I ran `xcprepare integrate` and it contains the following:

```
(lldb) settings show target.source-map
target.source-map (path-map) =
[0] "/xxxxxxxxxx" -> "/Users/csignori/Projects/iphone/vendor/cache/ruby/2.6.0/gems/ffi-1.15.4/ext/ffi_c/libffi"
```

- I also tried downloading the source code, checking out tag 0.3.7, adding `sleep(1)` to `XCPrebuild.main` and `XCPostbuild.main` and using the locally built `xcprepare integrate` as suggested on #92. The outcome was the same.

**Comment by polac24** [comment]
This is funny. 
Do you always get in `~/.lldbinit` the same path to `ffi_c` if you call that `xcprepare integrate` from different directories? I mean `cd ~; xcprepare integrate ...` or `cd ~/Desktop; xcprepare integrate ...`. 
Maybe you are calling `xcprepare` from ruby and it passes some magical extra params?

**Comment by cezarsignori** [comment]
No, where I call `xcprepare integrate` from does not affect the output. 

I think the problem is that each time I call `xcprepare integrate`, the `~/.lldbinit` file is overwritten and since I call it once for each xcodeproject file in my workspace, only the last execution content remains in the `~/.lldbinit` file.

How should the `~/.lldbinit` file look like for workspaces with hundreds of xcodeproject files? Is there another way to run the automatic integration without running into this problem? Should I create the `~/.lldbinit` file myself listing the paths for each xcodeproj? If so, should all the keys be `/xxxxxxxxxx`?

**Comment by polac24** [comment]
If you have multiple project, you need to manage `~/.lldbinit` manually. 
1. Pass `--lldb-init none `, see [here](https://github.com/spotify/XCRemoteCache#3b-consumer-side)
2. Manually add a root directory of all sources you want to compile to the `~/.lldbinit`:
```
settings set target.source-map /xxxxxxxxxx /Absolute/Path/Of/Your/All/Sources
```
3. Alternatively (if you cannot find a single root directory), you could play also with exclusive `--fake-src-root` passed for each project. That requires some more effort, so 2 is the preffered way.
```
settings set target.source-map /xxxxxxxxxx1 /some/dir
settings add target.source-map /xxxxxxxxxx2 /someOther/dir
...
```

**Comment by cezarsignori** [comment]
I passed `--lldb-init none` in each `xcprepare integrate` call, created the `~/.lldbinit` manually, opened Xcode, build and run and the debugger still did not work. 

The `~/.lldbinit` file points to my repository root:

<pre>
settings set target.source-map /xxxxxxxxxx /Users/csignori/Projects/iphone
</pre>

Shouldn't that work since all sources I want to compile are in there? (I also tried to specify the directory where the `xcworkspace` and root `xcodeproj` files are, same result.)

Meanwhile, I will work on alternative 2 (I think that will require to re-run the producer successfully since `--fake-src-root` must match between consumer and producer). I imagine the `--fake-src-root` value for each project should be the either the `xcodeproj` parent directory or their `Sources` folder?

**Comment by cezarsignori** [comment]
Unfortunately one `~/.lldbinit` entry per xcodeproj file did not work as well (I did build with producer and consumer using the same `~/.lldbinit`). 

On alternative 2, my `~/.lldbinit` file has 352 unique entries like so:

<pre>
settings set target.source-map /xxxxxxxxxx1 /Users/csignori/Projects/iphone/{app}/DMLProto/UI/ReviewsUI
settings set target.source-map /xxxxxxxxxx2 /Users/csignori/Projects/iphone/{app}/DMLProto/UI/PropertyLocationUI
settings set target.source-map /xxxxxxxxxx3 /Users/csignori/Projects/iphone/{app}/DMLProto/UI/RoomsUI
...
settings set target.source-map /xxxxxxxxxx8 /Users/csignori/Projects/iphone/{app}/DMLProto
settings set target.source-map /xxxxxxxxxx9 /Users/csignori/Projects/iphone/{app}/DMLProto/Workflow/PropertyPageWorkflow
....
</pre>

For testing alternative 2, these are the `xcprepare integrate` commands I ran for each project in the producer side:
<pre>
"{0}/xcremotecache/xcprepare integrate --input {1} --mode producer --final-producer-target {2} --lldb-init none --fake-src-root {3}".format(app_dir, xcodeproj_file, xcodeproj_main_target, lldbkey_for(project_num))
</pre>
and in the consumer side:
<pre>
"{0}/xcremotecache/xcprepare integrate --input {1} --mode consumer --lldb-init none --fake-src-root {2}".format(app_dir, xcodeproj_file, lldbkey_for(project_num))
</pre>

_Note: I used `settings set` instead of `settings add` because the later is not a valid command._

1. Do you spot any issues with these?
2. What is the correct content for `~/.lldbinit`? 
3. What else could be broken?

**Comment by polac24** [comment]
Let me focus on the second alternative, so far it looks promising.
1. I made a mistake, there should be `append` not `add`. If you use `set` all previous remaps (entries in `target.source-map`) will be erased. To wrap up: the expected ~/.lldbinit is:
```
settings set target.source-map /xxxxxxxxxx1 /Users/csignori/Projects/iphone/{app}/DMLProto/UI/ReviewsUI
settings append target.source-map /xxxxxxxxxx2 /Users/csignori/Projects/iphone/{app}/DMLProto/UI/PropertyLocationUI
settings append target.source-map /xxxxxxxxxx3 /Users/csignori/Projects/iphone/{app}/DMLProto/UI/RoomsUI
...
settings append target.source-map /xxxxxxxxxx8 /Users/csignori/Projects/iphone/{app}/DMLProto
settings append target.source-map /xxxxxxxxxx9 /Users/csignori/Projects/iphone/{app}/DMLProto/Workflow/PropertyPageWorkflow
....
```

You can verify that in runtime - pause the app and type in lldb: `settings show  target.source-map`. You should see a list of 352 entries

2. How to troubleshoot? Take one project (e.g. `/Users/csignori/Projects/iphone/{app}/DMLProto/UI/ReviewsUI`) and find build setting `XCRC_FAKE_SRCROOT`. It should match the one you have in ~/.lldbinit (e.g. `/xxxxxxxxxx1`  for `ReviewsUI`, `/xxxxxxxxxx2` for `PropertyLocationUI`).).

**Comment by cezarsignori** [comment]
Now it worked! Thank you!

But I had to fix a bug in RC to make it work. Unfortunately I can't seem to push my branch to open a PR.

<pre>
❯ git push origin csignori/xcrc_fake_src_root
ERROR: Permission to spotify/XCRemoteCache.git denied to cezarsignori.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
</pre>

Is the repo open to public contributions? 

Anyways, attached the patch for 0.3.7.

[xcrc_fake_src_root.patch.zip](https://github.com/spotify/XCRemoteCache/files/8223009/xcrc_fake_src_root.patch.zip)

**Comment by polac24** [comment]
Yes, we use forked stragy for PRs.

Thanks for the PR, I have 2 cosmetic comments:
* shouldn't the test class be called `XcodeProjBuildSettingsIntegrateAppenderTests`
* do you mind using `XCTUnwrap ` instead of force unwrwap? We prefer that to continue testing other testcases ([example](https://github.com/spotify/XCRemoteCache/blob/b6318e97855f8f23b2dc670a8765baad80340d25/Tests/XCRemoteCacheTests/Network/URLBuilderImplTests.swift#L26))
