### ISSUE TITLE
Use an instance profile or assume a role while accessing the S3 bucket

### ISSUE THREAD

**Issue by devMEremenko** [spotify/XCRemoteCache#108]
Hi XCRemoteCache Team,

We are going to run XCRemoteCache on EC2 Macs in AWS.

Is it possible to use an instance profile or assume a role while accessing the S3 bucket?

**Expected/desired behavior**
XCRemoteCache uses instance profile or assumes role while accessing S3 bucket

**Relevant integration setup**
[X] Automatic integration using `xcprepare integrate ...`

Thanks!

**Comment by polac24** [comment]
Hello!
I assume you want to host your artifacts on S3 and EC2 is an environment where XCRemoteCache clients will run.

In short: Yes
Details: To authorize XCRemoteCache clients into S3 you have to generate AWS access keys and according to Amazon's [docs](https://aws.amazon.com/premiumsupport/knowledge-center/create-access-key/) you can assign a profile to the IAM user. These AWS access keys should be added to the XCRemoteCache configuration described [here](https://github.com/spotify/XCRemoteCache#amazon-s3-and-google-cloud-storage).

**Comment by devMEremenko** [comment]
Hi @polac24,

Thanks for the reply!

Unfortunately, it's forbidden to use static keys for security reasons.

I've added support for [AWS Temporary Access Keys](https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#temporary-access-keys) as an alternative authorization method.

Let me know your thoughts [there](https://github.com/spotify/XCRemoteCache/pull/111) 😃
