### ISSUE TITLE
Can I turn off XCRemoteCache? For instance, when the internet connection is slow or data usage is limited.

### ISSUE THREAD

**Issue by devMEremenko** [spotify/XCRemoteCache#115]
Hi XCRemoteCache Team,

**Context**
XCRemoteCache assumes that downloading prebuilt artifacts is faster than recomputing new ones.
However, this statement might not be true when the internet connection is slow or data usage is limited. Moreover, users may have other reasons to temporary turn off XCRemoteCache (like dealing with some specific bug, unavailability of a remote cache service, etc)

**Expected/desired behavior**
That's why I am thinking about the `is_enabled` field in the `.rcinfo` file to temporarily turn off XCRemoteCache and switch to the compilation mode.

Let me know if XCRemoteCache already contains such a feature 🙂

**Relevant integration setup**

[X] CocoaPods cocoapods-xcremotecache plugin
[X] Automatic integration using `xcprepare integrate ...`
[X] Manual integration
[X] Carthage

**Comment by polac24** [comment]
Hi! There are many ways to achieve that:
* delete the file passed in`remote_commit_file`
* in the `xcprepare mark`, you can pass `--targets-include=None`
* set `cache_commit_history: 0`

all of them are more workarounds so why not having an explicit `is_enabled` config? I like the idea.

**Comment by dwirandyh** [comment]
+1
i have this issue as well, it will be great to be added

**Comment by devMEremenko** [comment]
Hi @polac24,

Thank you for the suggested ideas!

I like this one as a temporary solution: `cache_commit_history: 0`
I am going contribute `is_enabled` _soon_.
