### ISSUE TITLE
Calling `xcprepare --configuration --platform` errors when invoked from `Build -> Pre-actions`

### ISSUE THREAD

**Issue by devMEremenko** [spotify/XCRemoteCache#119]
**My integration setup**

[ ] CocoaPods cocoapods-xcremotecache plugin
[x] Automatic integration using `xcprepare integrate ...`
[ ] Manual integration
[ ] Carthage

**Context**

ReadMe has the following comment:
> Execute xcprepare --configuration #Configuration# --platform #platform# command after each merge or rebase with the primary branch. Otherwise, the remote cache artifacts may be outdated, and the final hit rate may be poor.

Since I do not want to run this manually each time, I considered using `Xcode -> Scheme -> Build -> Pre-actions`. 
For instance:
   - `xcprepare --configuration ${CONFIGURATION} --platform ${SDKROOT}`
       - `xcprepare --configuration Debug --platform iphoneos`
       - `xcprepare --configuration Debug --platform iphonesimulator`

However, when `xcprepare` is called from Pre-actions, I receive the following log:

<details>
  <pre>
error: Prepare failed with error: statusError("status 1: clang: warning: using sysroot for \'iPhoneOS\' but targeting \'MacOSX\' [-
Wincompatible-sysroot]\nIn file included from /var/folders/sf/wlbxpcjx1y5bq23sd_c41kbh0000gp/T/xccc.c:9:\nIn file included from
/Applications/Xcode-13-
3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/fcntl.h:23:\nIn file included from /Applications/Xcode-13-
3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/sys/fcntl.h:78:\nIn file included from /Applications/Xcode-13-
3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/sys/_types.h:32:\n/Applications/Xcode-13-
3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/sys/cdefs.h:870:2: error: 
Unsupported architecture\n#error Unsupported architecture\n ^\nIn file included from 
/var/folders/sf/wlbxpcjx1y5bq23sd_c41kbh0000gp/T/xccc.c:9:\nIn file included from /Applications/Xcode-13-
3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/fcntl.h:23:\nIn file included 
from /Applications/Xcode-13-
3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/sys/fcntl.h:78:\nIn file 
included from /Applications/Xcode-13-
3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/sys/_types.h:33:\n/Applica
tions/Xcode-13-
3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/machine/_types.h:34:2: 
error: architecture not supported\n#error architecture not supported\n ^\n

...

 </pre>
</details>

I receive errors above when `SDKROOT` is set to `iphoneos` / `iphonesimulator` and a remote cache server has artifacts.

I tried to `unset SDKROOT` (I assume this leads to using a default value - `macosx`) that "solved" a problem.
However, I am unsure if this approach (and updated files) is actually correct to use.

As far as I understand, `xcprepare` internally calls `xcrun ...` and, for some reason, it targets `macosx` SDK.

**Expected/desired behavior**

Calling `xcprepare --configuration ${CONFIGURATION} --platform ${SDKROOT}` from `Pre-actions` works without errors above.
Let me know if you have other ideas for achieving the desired behavior.

**Minimal reproduction of the problem with instructions**
- Open a scheme settings
- Go to `Build -> Pre-actions`
- Add a new script `xcprepare --configuration ${CONFIGURATION} --platform ${SDKROOT}`

**xcprepare logs**

<details>
  <pre>
2022-04-12 17:45:46.654 I  xcprepare[73275:a320f4] ClangWrapperBuilder compiles file at file:///var/folders/sf/wlbxpcjx1y5bq23sd_c41kbh0000gp/T/xccc.c.
2022-04-12 17:45:46.855 E  xcprepare[73275:a320f4] Prepare failed with error: statusError("status 1: clang: warning: using sysroot for \134'iPhoneOS\134' but targeting \134'MacOSX\134' [-Wincompatible-sysroot]\134nIn file included from /var/folders/sf/wlbxpcjx1y5bq23sd_c41kbh0000gp/T/xccc.c:9:\134nIn file included from /Applications/Xcode-13-3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/fcntl.h:23:\134nIn file included from /Applications/Xcode-13-3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/sys/fcntl.h:78:\134nIn file included from /Applications/Xcode-13-3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/sys/_types.h:32:\134n/Applications/Xcode-13-3.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/sys/cdefs.h:870:2: error: Unsupported architecture\134n#error Unsupported architecture\134n ^\134nIn file included from /var/folders/sf/wlbxpcjx1y5bq23sd_c41kbh0000gp/T/xccc.c:9:\134nIn file inclu<…>
 </pre>
</details>

**Environment**

* **XCRemoteCache:** 0.3.9
* **HTTP cache server:** AWS
* **Xcode:** 13.3 13E113

**Comment by polac24** [comment]
I am afraid that calling `xcprepare` from prebuild is not a good approach. For each Xcode build (even incremental or "no-operation" build), HTTP requests to your remote servers will be triggered. That slows down a feedback loop. Please keep in mind that XCRemoteCache is optimized so to invoke blazing fast wrappers like `xccc` but for the cost of relatively slow `xcprepare`. Rationale: number of times you call `xccc` is tens, if not hundreds times higher.

Owing to that, I don't consider that as a bug.

**Comment by devMEremenko** [comment]
@polac24, thank you for your feedback. 

Indeed, xcprepare is relatively slow. To solve that, I currently store metadata to a file (a commit, Xcode version, etc). I then compare it with current values to skip xcprepare execution if nothing is changed.

The only downside of this approach is maintaining and adding a pre-build phase to every new scheme. 
To solve this:
- schemes can be generated
- pbxproj can be parsed, and a new pre-build phase is automatically added if it does not exist.

Could you provide peace of advice on where to start the investigation of this issue?
I am not thoroughly familiar with the internals of XCRemoteCache

Thanks! 🙏

**Comment by polac24** [comment]
You can find the `integrate` implementation here: https://github.com/spotify/XCRemoteCache/tree/master/Sources/XCRemoteCache/Commands/Prepare/Integrate

.xcodeproj manipulation happens in `XcodeProjIntegrate` ([link](https://github.com/spotify/XCRemoteCache/blob/master/Sources/XCRemoteCache/Commands/Prepare/Integrate/XcodeProjIntegrate.swift#L182-L219  ))

**Comment by polac24** [comment]
This is not a bug - `xcprepare` should not be called from Scheme's preaction.
