### ISSUE TITLE
how can i debug the source code

### ISSUE THREAD

**Issue by yangfan0210** [spotify/XCRemoteCache#120]
how can i debug the source code 

**Expected/desired behavior**

**Relevant integration setup**

[ ] CocoaPods cocoapods-xcremotecache plugin
[ ] Automatic integration using `xcprepare integrate ...`
[ ] Manual integration
[ ] Carthage

**Comment by polac24** [comment]
Available at https://github.com/spotify/XCRemoteCache/blob/master/docs/Development.md
