### ISSUE TITLE
`EnvironmentFingerprintGenerator` contains unused code

### ISSUE THREAD

**Issue by devMEremenko** [spotify/XCRemoteCache#142]
**Expected/desired behavior**

Hi!

I noticed that `EnvironmentFingerprintGenerator` declares [private generatedFingerprint](https://github.com/spotify/XCRemoteCache/blob/3b614c6172ffa50b39163ee25325533beca93029/Sources/XCRemoteCache/Fingerprint/EnvironmentFingerprint.swift#L40) variable 

```swift
private var generatedFingerprint: RawFingerprint?
```

However, there is no mutation, only accessing the initial (nil) value:

```swift
if let fingerprint = generatedFingerprint {
    return fingerprint
}
```

I assume that:
- it is a leftover, and the related code should be deleted
- it is an incompleted caching approach, and the value should be updated at the end of `generateFingerprint()` function.

I would fix it if I knew the initial intention.

**Comment by polac24** [comment]
Hi! It is the latter case - an incomplete optimization.
