### ISSUE TITLE
Support for Cocoapods's generate_multiple_pod_projects feature

### ISSUE THREAD

**Issue by CharlieSuP1** [spotify/XCRemoteCache#155]
Great remote cache project, and seems to work very in my Demo project, very promising！Thx a lot!

But when I try to integrate XCRemoteCache in my company's non-trivial project，I got very low cache hit rate.

After investigation, I found that cocoapods-xcremotecache plugin seems do not support Cocoapod's generate_multiple_pod_projects feature. Any cocoapods project(not target) do not have a XC** build phase.

And I looked into the code base, found there are actually efforts to support generate_multiple_pod_projects:

![image](https://user-images.githubusercontent.com/30035448/177822697-3b9eb059-3ff2-49d1-a529-91ac72713de5.png)

So I want to ask is there any progress in supporting generate_multiple_pod_projects?  Or are PRS related with generate_multiple_pod_projects welcome?

**Comment by polac24** [comment]
That is fully supported, added in #57 by @vasvf (with further improvements).

I have just double-checked the sample `Podfile` we use in the E2E tests, and the project correctly adds [XCRC] Build phases. Sample project's target:
<img width="727" alt="Screenshot 2022-07-07 at 18 46 31" src="https://user-images.githubusercontent.com/9629417/177827350-3f036833-9ca7-43d9-9fbf-0eee0634f65e.png">

**Comment by CharlieSuP1** [comment]
Thx for reply! 

I found the reason is that the feature Cocoapods' feature incremental_installation is also on. So the pod projects are not generated agin, thus no build phase inserted. 

In our project 
`  install!('cocoapods',
               incremental_installation: true,
               generate_multiple_pod_projects: true)`

I am not sure whether there is any way to insert XCR build phases with incremental_installation being true.

Thx again

**Comment by polac24** [comment]
That happens because you generated all Pod's .xcodeprojs before integrating with XCRemoteCache and cocoapods does not generate them anymore, even it should.

I think you have 2 workarounds to force pods project regeneration:
* `pod deintegrate` + `pod install` (maybe even `rm -rf Pods` is required)
* change to `install!('cocoapods', incremental_installation: false, generate_multiple_pod_projects: false)`  and generate a project once and then revert to the original `Podfile` state.

**Comment by polac24** [comment]
The ^ PR should fix that problem.

In the meantime, you can call `pod install --clean-install` if Pod's project/target misses [XCRC] integration build steps.

**Comment by CharlieSuP1** [comment]
thx a lot
