### ISSUE TITLE
Is producer-fast mode ready for production environment?

### ISSUE THREAD

**Issue by CharlieSuP1** [spotify/XCRemoteCache#168]
I noticed there is 'producer-fast' mode, which is a producer mode, but try to build unchanged projects with remote cache.

And the producer-faster mode is marked with 'experimental',  and I wonder why is that? Is producer-fast mode already used in production environment in Spotify?

**Comment by polac24** [comment]
This mode has never been verified in a big project and thus marked as experimental.

**Comment by CharlieSuP1** [comment]
in hooks.rb，prebuild is disabled for producer-fast mode，is it right? 
`  
     elsif mode == 'producer' || mode == 'producer-fast'
          # Delete existing prebuild build phase (to support switching between modes)
          target.build_phases.delete_if do |phase|
            if phase.respond_to?(:name)
              phase.name != nil && phase.name.start_with?("[XCRC] Prebuild")
            end
          end
        end
`

In SwiftcOrchestrator.swift, line 121, prebuild step seems to be a must to generate rcenable file.

**Comment by polac24** [comment]
Your concern seems legit, that looks like a bug.
