### ISSUE TITLE
Unknown problem after migrated to XCode14

### ISSUE THREAD

**Issue by canhth** [spotify/XCRemoteCache#173]
**My integration setup**
- CocoaPods cocoapods-xcremotecache plugin

**Problem description**
- In the past, we used Xcode 13.4.1 to build our project in CI. But after migrating to Xcode 14.0, we got a weird issue with a framework inside a Flutter package. 
 - It is still okay if we use the old Xcode 13.4.1 and the MoonImCoreSwift generated by 13.4.1.
 ```
 /Users/canhtran/Library/Developer/Xcode/DerivedData/MyApp-hbydakxttvkkggdnfmcfqpdwplfx/Build/Intermediates.noindex/MoonImCoreSwift.build/Dev Debug-iphonesimulator/MoonImCoreSwift.build/Objects-normal/x86_64/MoonImCoreSwift.private.swiftinterface: No such file or directory (in target 'MoonImCoreSwift' from project 'MoonImCoreSwift')
```
(MoonImCoreSwift  is the source code compile pod)

**Questions**
- Is there any potential problem that might cause this issue? 
- Or something specific we need to support for Xcode14?

**Environment**
- XCRemoteCache: 0.3.17
- cocoapods-xcremotecache: 0.0.14
- **HTTP cache server:**docker
- Xcode: 14.0 (14A309)

**Comment by canhth** [comment]
Hi @polac24,
May I ask about your thought/idea to fix this issue?
My team has disabled RemoteCache to make the CI works again.

**Comment by polac24** [comment]
Xcode 14 changed the way Swift's SPI is generated and produces `.private.swiftinterface` for Library evolution/distributable mode, next to the `.swiftinterface` file. 
You can either disable the evolution mode in that `MoonImCoreSwift` (which is always recommended unless you really want to distribute that library) or try to fix XCRemoteCache. Hopefully, that change will be simple, something like [here](https://github.com/polac24/XCRemoteCache/commit/0a648934895e4c7eb01c67f65be4845404299630)

I tried to reproduce the error in a sample project but couln;t find a way to force swift compiler relying on a .private.swiftinterface but at glance, it looks, it will just work.

_Sidenote: I also included in a commit bundling abi.json. Don't know if that is required in Xcode 14 so if you have a real-world project, you can check that too._

**Comment by canhth** [comment]
Hi @polac24,
Yes, you're right. 
The error is gone when disabling `BUILD_LIBRARY_FOR_DISTRIBUTION` option for `MoonImCoreSwift`.
But I am afraid the other team won't accept that option, there must be some reason that they enabled it for Flutter package.

I tried your branch [here](https://github.com/polac24/XCRemoteCache/tree/polac24-private-swiftinterface), generate the release package, and replace it with my real project. 
```
'product_files_extensions_with_content_override' => ["swiftmodule", "h", "private.swiftinterface", "abiJson"]
```
Unfortunately, it doesn't work. Or did I miss something?

**Comment by polac24** [comment]
I think you don't need to add anything to `product_files_extensions_with_content_override`, updating the producer and consumer's XCRemoteCache library from a [branch](https://github.com/polac24/XCRemoteCache/tree/polac24-private-swiftinterface) should be enough.

If that still doesn't work: make sure the zip file the producer creates for `MoonImCoreSwift` contains `.private.swiftinterfact`  next to the `.swiftinterface`.

**Comment by canhth** [comment]
<img width="872" alt="Screen Shot 2022-11-15 at 10 33 08" src="https://user-images.githubusercontent.com/7752679/201820175-b9118c4b-a06a-472a-9271-3cdba05cf7c9.png">
Hi @polac24 ,
Yes, the zip producer of `MoonImCoreSwift` contains all the new options (abi.json, private.swiftinterface).

**Comment by polac24** [comment]
Hmmm, can you double-check that your local cache is not reusing previous artifacts on the consumer sides (e.g. nuke `~/Library/Caches/XCRemoteCache` or `artifact_maximum_age: 0` in .rcinfo)?

I wrote some tests and everything seems to play well with that. Created even a PR: #175. If that doesn't work, probably you have to debug it locally: https://github.com/spotify/XCRemoteCache/blob/master/docs/FAQ.md

**Comment by canhth** [comment]
Hi @polac24,
It works after I clear the local cache. Thanks a lot.
May I ask when we can have a `New Release` contains this [PR](https://github.com/spotify/XCRemoteCache/pull/175)?

The issue was getting the wrong `fileKey`.
(the producer job still running every day, maybe it always fetch the latest fileKey which does not support `.private.swiftinterface` yet)

**Comment by polac24** [comment]
once we get +1 review, I can make a new release. Probably that will be in 2-3 days.

to workaround, maybe you can:
1. either change the directory where the new cache puts data (e.g. https://s3.aws.../cache_1 (recommended)
2. or temporarily set `artifact_maximum_age:1` and nuke your remote cache server's storage. After day-two, you can move `artifact_maximum_age` to the previous value.

**Comment by polac24** [comment]
Included in https://github.com/spotify/XCRemoteCache/releases/tag/v0.3.18
