### ISSUE TITLE
error: XCRemoteCache cannot be initialized with a consumer mode. Error: noArtifactsToReuse.

### ISSUE THREAD

**Issue by akring** [spotify/XCRemoteCache#21]
Xcode config: Automatic integration

Backend: backend-example docker image

I completed all the configs and setups, and build succeed with `producer ` mode. However when I tried with `xcremotecache/xcprepare integrate --input xxx.xcodeproj --mode consumer`, I got "error: XCRemoteCache cannot be initialized with a consumer mode. Error: noArtifactsToReuse."

I crawled all the network traffic during build and `xcremotecache/xcprepare integrate --input xxx.xcodeproj --mode consumer`, and found that what I uploaded to the server during build, is not `matched` with all the request later.

![CleanShot 2021-11-22 at 18 24 29@2x](https://user-images.githubusercontent.com/6525286/142846233-af2bd90d-1bd0-4c1a-9c35-4fd863bd83e9.png)

**Comment by polac24** [comment]
@akring , did you run the `producer` mode on a primary branch (defaults to `master`)? 
Looks that the `fd18076` commit is not part of this branch and `xcprepare` tries to find older commits on a primary branch (`f9d329`, `50a2279` etc.).

**Comment by akring** [comment]
> 

Yeah, my bad. Build with `master` solved the problem
