### ISSUE TITLE
Is there a parameter that can suppress the output of logs，such as xcodebuild --silent

### ISSUE THREAD

**Issue by Coder-Star** [spotify/XCRemoteCache#219]
**Expected/desired behavior**

**Relevant integration setup**

[ ] CocoaPods cocoapods-xcremotecache plugin
[ ] Automatic integration using `xcprepare integrate ...`
[ ] Manual integration
[ ] Carthage

**Comment by Coder-Star** [comment]
It should be Xcode。
Let me give you a rough idea of the scenarios I encountered，I am compiling a project as a consumer on a CI machine, and the output log is very large

**Comment by polac24** [comment]
Logs from XCRemoteCache are not available from Xcode or `xcodebuild`, except the summary `[RC] Cached build for` or `[RC] Disabled remote cache for` log. Can you give an example log you would like to suppress?
