### ISSUE TITLE
Prebuild step failed with error: unsuccessfulResponse(status: 404)

### ISSUE THREAD

**Issue by amiit** [spotify/XCRemoteCache#228]
**My integration setup**

[ ] CocoaPods cocoapods-xcremotecache plugin

**Expected/desired behavior**
remote caching should work

**Minimal reproduction of the problem with instructions**
Updated Podfile with below code:
 
plugin 'cocoapods-xcremotecache'
xcremotecache({
  'cache_addresses' => ['https://PROJECT_NAME.s3.ap-south-1.amazonaws.com/'],
  'primary_repo' => 'git@bitbucket.org/PROJECT_NAME.git',
  'mode' => 'consumer',
  'final_target' => 'PROJECT_NAME',
  'primary_branch' => 'develop',
  'aws_secret_key' => 'SECRET_KEY',
  'aws_access_key' => 'ACCESS_KEY',
  'aws_region' => 'ap-south-1',
  'aws_service' => 's3'
})

After this run 'pod install' which printed in the console:
[XCRC] XCRemoteCache enabled

From same machine separately via Automatic integration option, I added producer mode and from the same branch(develop) updated the cache in the remote (can see file/marker/meta related to latest commit in the S3 bucket). 

Now when I am running project for consumer mode as mentioned in the above podfile, Its not using cache data and for every pod including final_target project I can see the message in the Xcode build log:
[RC] Disabled remote cache

I am using static libraries. I am not getting what is going wrong here. For producer mode everything is working fine (via automatic integration) but for consumer mode its not using cache. This consumer mode issue is coming for both automatic integration as well as for cocoapods plugin. Please help me in identifying what is going wrong here and how to fix this? 

**Producer Logs**
No issues here

**Consumer Logs**
<details>
  <pre> 
 xcprebuild[57101:48ce29] (AFNetworking) Prebuild step failed with error: unsuccessfulResponse(status: 404)
 Df xcswiftc[57437:48d178] Fallbacking to compilation using swiftc.
 xcprebuild[5975:4b2bab] (PROJECT_NAME) Prebuild step failed with error: artifactLocationIsUnknown
</pre>
</details>

**Pods/Carthage file**
<details>
  <pre> 
plugin 'cocoapods-xcremotecache'
xcremotecache({
  'cache_addresses' => ['https://PROJECT_NAME.s3.ap-south-1.amazonaws.com/'],
  'primary_repo' => 'git@bitbucket.org/PROJECT_NAME.git',
  'mode' => 'consumer',
  'final_target' => 'PROJECT_NAME',
  'primary_branch' => 'develop',
  'aws_secret_key' => 'SECRET_KEY',
  'aws_access_key' => 'ACCESS_KEY',
  'aws_region' => 'ap-south-1',
  'aws_service' => 's3'
})
</pre>
</details>

**Environment**

* **XCRemoteCache:** X.Y.Z
* **cocoapods-xcremotecache:** X.Y.Z <!-- check with `gem list cocoapods-xcremotecache` >
*-> 0.0.18
* **HTTP cache server:** ... <!-- e.g. demo docker, nginx, AWS etc. >
* -> AWS
* **Xcode:** X.Y.Z
* -> 14.2

**Post build stats**
**Others**

**Comment by polac24** [comment]
Hi! 
If I understand correctly, you want to generate artifacts from the "automation integration" but use them in the cocoapods mode. That is not supported. You have to produce and consume artifacts with the same integration.  

So you have to pass `'mode' => 'producer',` in the `Podfile` to produce artifacts.

**Comment by amiit** [comment]
Hi @polac24 
Thanks for quick response. I tried producer and consumer both via pod option only still getting same issue during consumer mode:
 xcprebuild(POD_NAME) Prebuild step failed with error: unsuccessfulResponse(status: 404)

and for every pod this line I can see in the Xcode build logs:
[RC] Disabled remote cache for POD_NAME

During 'pod install' I am getting remote cache enabled log. All these are static pods I am using in my project.

Is there anything else I am missing?

**Comment by polac24** [comment]
There are many possible reasons like different configurations (Debug/Release etc.) or some targets are not stored on the server. 
I recommend looking for your logs ([docs](https://github.com/spotify/XCRemoteCache/blob/master/docs/FAQ.md#how-can-i-find-xcremotecache-logs)) on the consumer side to see which file get 404 and why it doesn't existing in s3:
```
log show --predicate 'sender BEGINSWITH "xc"' --style compact --info --debug -last 10m
``` 
and also [this](https://github.com/spotify/XCRemoteCache/blob/master/docs/FAQ.md#troubleshooting-cache-misses) list might be helpful

**Comment by amiit** [comment]
Thanks @polac24 , it's working now :)
