### ISSUE TITLE
XCRemoteCache disabled with error: 403 rate limit exceeded

### ISSUE THREAD

**Issue by ruzhuxiaogu** [spotify/XCRemoteCache#26]
XCRemoteCache disabled with error: 403 rate limit exceeded

**Comment by polac24** [comment]
Hi @ruzhuxiaogu! Can you provide more context when did that error happen? Was that coming from the cocoapods plugin in the `pod install` phase maybe?

**Comment by ruzhuxiaogu** [comment]
Thanks for your reply, this question is solved, but when excute pod install, a new question occured, [XCRC] XCRemoteCache failed with an error: undefined method `[]' for false:FalseClass.

**Comment by polac24** [comment]
The original problem seems to be solved.
