### ISSUE TITLE
"error: missing input file" during building as a consumer

### ISSUE THREAD

**Issue by akring** [spotify/XCRemoteCache#37]
Xcode config: Automatic integration

Backend: backend-example docker image

Error log:

```
error: missing input file
/Users/xxx/Library/Developer/Xcode/DerivedData/MyProject-grtwydkopfrbzbfwavurkuenidfb/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/7220286051759018287/MyProject-prefix.pch.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'Target' from project 'MyProject')
Command ProcessPCH++ failed with a nonzero exit code
```

This happened during build as consumer. I had upload all the files to my server with producer mode.
I crawled the network during build, and all the `GET` request from the server is succeed.

**Comment by wfanforever** [comment]
same issue here, as a workaround you can try disable the precompile prefix header in consumer mode.

**Comment by akring** [comment]
> 

Thanks, but that's not a good idea for an Objective-C project 😂

**Comment by SeanWit** [comment]
same issue

**Comment by samuelsainz** [comment]
This is happening to me as well

**Comment by iSalah** [comment]
Same issue here.
I've noticed that Xcode is trying to build my project with the "c-header" language parameter (-x)  instead of "objective-c-header",  that's why @polac24 fix is not working for me.

Does someone have any idea why ?
I'm using Xcode 14.1 and my project has both ObjC and Swift code.

**Comment by polac24** [comment]
Hi @iSalah, could you provide a sample project? However, I created a blind patch #177 so maybe you can first verify if that fixes your issue for `c-header`.

**Comment by iSalah** [comment]
Thak you @polac24.
How can I build the xccc wrapper from your branch to test the fix ? There are several targets I can build (xcprepare, xcprebuild, ...) but no xccc.

**Comment by polac24** [comment]
Hi @iSalah!
> A wrapper for the clang compilation is a C program, generated and compiled during the xcprepare step

It has a custom flow, for better performance. You can read more about that [here](https://github.com/spotify/XCRemoteCache#performance-optimizations)

**Comment by iSalah** [comment]
@polac24 I confirm it works with your fix, thank you !
