### ISSUE TITLE
error: XCRemoteCache cannot be initialized with a consumer mode. Error: noArtifactsToReuse.

### ISSUE THREAD

**Issue by chbo297** [spotify/XCRemoteCache#38]

**Comment by polac24** [comment]
Hi @chbo297 ! Can you provide more details: logs, see [How To Get Logs](https://github.com/spotify/XCRemoteCache/blob/master/docs/FAQ.md#how-can-i-find-xcremotecache-logs), are you on M1 machine etc.?
