### ISSUE TITLE
Fix swiftlint warnings

### ISSUE THREAD

**Issue by polac24** [spotify/XCRemoteCache#4]
Swiftlint reports warnings so non-strict linting is performed. Fix all warnings and enabled `strict` linting mode.

**Comment by woodencoder** [comment]
Hi @polac24!
There seems to be a lot of issues with `trailing_dot_in_comments` which causes a generic file header to violate SwiftLint rules
```swift
// Copyright (c) 2021 Spotify AB. – violates
// Copyright (c) 2021 Spotify AB – passes
```

Should we maybe disable that rule in `.swiiftlint.yml`?

**Comment by polac24** [comment]
I am fine to relax our linting rules and get rid of `trailing_dot_in_comments`.

**Comment by polac24** [comment]
Fixed by https://github.com/spotify/XCRemoteCache/pull/24
