### ISSUE TITLE
The certificate for this server is invalid

### ISSUE THREAD

**Issue by alekzernov** [spotify/XCRemoteCache#50]
We use certificates for servers that are not validated. I get an error when using **error: Prepare failed with error: other(Error Domain=NSURLErrorDomain Code=-1202 "The certificate for this server is invalid. You might be connecting to a server that is pretending to be which could put your confidential information at risk." UserInfo={NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSErrorPeerCertificateChainKey=( ...**
I made a revision in XCRemoteCache.  Сan i push it?

**Comment by polac24** [comment]
Hi! Not sure if I get it. 
Am I right that your cache server uses HTTPS but the certificate is not trusted and xcprebuild fails with an error? If so, did you try adding that certificated to the keychain and trust it?
Not sure what change in XCRetemoCache you expect? To disable certificate verification?

**Comment by alekzernov** [comment]
> Hi! Not sure if I get it. Am I right that your cache server uses HTTPS but the certificate is not trusted and xcprebuild fails with an error? If so, did you try adding that certificated to the keychain and trust it? Not sure what change in XCRetemoCache you expect? To disable certificate verification?

Yes, you understood me correctly. I want a parameter that would disable the verification of certificates.
I added a parameter through which you can disable the verification of certificates. I have a thread that. I can push changes to your repository. You look and decide whether to leave or not. Because I don't want to lose new changes because of a small flag

**Comment by polac24** [comment]
Sure, as long as this will be opt-in, we can merge it.

**Comment by alekzernov** [comment]
> Sure, as long as this will be opt-in, we can merge it.

I do not have enough rights to push my branch to your repository

**Comment by polac24** [comment]
we follow forking strategy - fork a repo, push a branch there and create a PR from it.

**Comment by alekzernov** [comment]
> we follow forking strategy - fork a repo, push a branch there and create a PR from it.

https://github.com/spotify/XCRemoteCache/pull/51
