### ISSUE TITLE
json file contains direct paths

### ISSUE THREAD

**Issue by DRybochkin** [spotify/XCRemoteCache#59]
![image](https://user-images.githubusercontent.com/5586021/151069612-251d914c-701f-4eb4-b092-12209f52e0a0.png)

**Comment by polac24** [comment]
Can you provide more steps to reproduce? I see that you use Pods but the following Podfile doesn't reproduce it:
```
target 'Name' do
  use_frameworks!
  pod 'ReactiveSwift'
end
```
I assume that `/Users/*/` is just a redacted username. Do you have any non-ascii chars in the username maybe?

Am I right that you have some out_of_band_mappings replacements with `SUPER_TARGET_SRCROOT`. Do you think it may cause this issue?

**Comment by DRybochkin** [comment]
yes it is a redacted username and username does not have any non-ascii chars

**Comment by DRybochkin** [comment]
I don't think so, because if you comment out_of_band_mappings, then the direct path to the folder with the developer modules will appear, and the path to module.modulemap will not change

./ProjectFolder
./ProjectFolder/DeveloperPodsSourse <=> SUPER_TARGET_SRCROOT
./ProjectFolder/Pods

in my opinion this happens because BUILD_DIR = DerrrivedData/../Build/Products
and module.modulemap is in DerrivedData/../Intermediates.noindex/Pods.build which is not replaced

Build location is default

![image](https://user-images.githubusercontent.com/5586021/151274579-f38e0a63-7d16-4e37-a197-5dcba196d0ee.png)

**Comment by polac24** [comment]
I recall that error but AFAIR it was always my misconfiguration. Keep in mind that there is a cache on your local machine at `~/Library/Caches/XCRemoteCache` and it may contain some outdated (aka polluted) entries.

Tip: When playing with XCRemoteCache and/or trying to integrate it into a new project, I always set `artifact_maximum_age:0` to practically disable the local cache. It might be a case.

**Comment by DRybochkin** [comment]
https://github.com/DRybochkin/TestXCRC
Link to the test project where the error is reproduced

**Comment by polac24** [comment]
Thanks for the project. I was able to reproduce it. When dynamic libraries are used, Xcode passes vfsoverlays configuration to the swift compiler but XCRemoteCache doesn't substitute the underlying raw file with the overlay's location (in `Products`). 
This is definitely a missing feature that XCRemoteCache should cover.
