### ISSUE TITLE
Error: Cannot run project that depends on .framework file

### ISSUE THREAD

**Issue by dwirandytlvk** [spotify/XCRemoteCache#60]
Hi there,
I try `XCRemoteCache` `cocoapods plugin` in simple project and it works well.
But after i add a `Firebase/Analytics` and doing pod install i always got this error

<img width="1059" alt="Screen Shot 2022-01-26 at 16 16 35" src="https://user-images.githubusercontent.com/93510180/151135745-989b22fb-460e-48f5-aede-72f190020b61.png">
 
I think it's because the `Firebase/Analytic` dependency is a `.framework` instead of `source file`

May i know how to solve this issue?

**Comment by polac24** [comment]
It is a bug in the CocoaPods plugin, fixing in #61.

As a workaround, you can manually add them to the list of excluded targets in a `Podfile`:
```
xcremotecache({
...
  'exclude_targets' => ['Firebase', 'FirebaseAnalytics', 'GoogleAppMeasurement']
})
```

**Comment by dwirandytlvk** [comment]
thanks for your help @polac24
