### ISSUE TITLE
Large memory allocation when running the XCBBuildService

### ISSUE THREAD

**Issue by DRybochkin** [spotify/XCRemoteCache#76]
When the project is built without XCRemoteCache, then there is no such problem
![image](https://user-images.githubusercontent.com/5586021/153382756-d28fbb8b-8d7f-49b6-9b71-92cb0a698e6b.png)

it started with version 0.0.5 or 0.0.6
did not notice this in version 0.0.4

**Comment by polac24** [comment]
Can you verify with version XCRemoteCache 0.3.6?

**Comment by polac24** [comment]
Probably fixed in #85. Please reopen if it reappears
