### ISSUE TITLE
when the target have dependencies can not hit the cache

### ISSUE THREAD

**Issue by xwlxwl** [spotify/XCRemoteCache#84]
I found that when the target have dependencies ,it can not hit the cache.But if the target have no any dependencies ,it can hit cache 100%

**Comment by vasvf** [comment]
duplicate of #80 ?

**Comment by xwlxwl** [comment]
> duplicate of #80 ?
how can I look hit count and missing count in logs

**Comment by vasvf** [comment]
@xwlxwl you can use this command:
`./XCRC/xcprepare stats`

**Comment by polac24** [comment]
@xwlxwl, please verify with version 0.3.6

**Comment by xwlxwl** [comment]
> @xwlxwl, please verify with version 0.3.6
Thanks, i will try it

**Comment by xwlxwl** [comment]
> > @xwlxwl, please verify with version 0.3.6
> > Thanks, i will try it

hit_count: 502
miss_count: 2956
local_cache_bytes: 108703744
indexing_hit_count: 557
indexing_miss_count: 3987

**Comment by xwlxwl** [comment]
> hit_count: 502
> miss_count: 2956
> local_cache_bytes: 108703744
> indexing_hit_count: 557
> indexing_miss_count: 3987

hit_count: 502
miss_count: 2956
local_cache_bytes: 108703744
indexing_hit_count: 557
indexing_miss_count: 3987
